scannect/scannect/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'', include('scannect_web.urls')),
    url(r'admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
]

scannect/scannect_web/urls.py
from django.urls import path

from .views import user, visitor

urlpatterns = [

    # For unregistered users
    path('', visitor.home, name='home'),
    path('signup', visitor.signup, name='signup'),
    path('logout', visitor.logout_user, name='logout'),
    path('detail/<int:id>', visitor.detail, name='detail'),
    path('models/<int:user>', visitor.user_models, name='visit_user'),
    path('guide', visitor.guide, name='guide'),
    path('download_scannect', visitor.download_scannect, name='download_scannect'),
    path('stream', visitor.stream, name='stream'),

    # For logged in users
    path('upload', user.upload, name='upload'),
    path('upload/tmp', user.tmp_file, name='tmp_model'),
    path('myscans', user.user_models, name='myscans'),
    path('favourites', user.favourites, name='favourites'),
    path('profile', user.profile, name='profile'),
    path('edit/profile', user.settings, name='settings'),
    path('edit/password', user.change_password, name='change_password'),
    path('delete/user', user.delete_account, name='delete_account'),
    #path('edit/model/<int:id>', user.edit, name='edit'),
    path('delete/model/<int:id>', user.delete_model, name='delete_model'),
    path('upvote/<int:id>', user.upvote, name='upvote'),
    path('favourite/<int:id>', user.favourite, name='favourite'),

]

scannect/scannect_web/models/user_models.py
import os

from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.db.models.signals import post_save, pre_save, post_delete, pre_delete
from django.dispatch import receiver

from scannect.settings import MEDIA_ROOT
from .scan_models import ScanModel

def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class CustomUser(User):
    class Meta:
        proxy = True

    username_validator = ASCIIUsernameValidator()


class Profile(models.Model):
    class Meta:
        db_table = 'profile'
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    upvotes = models.ManyToManyField(ScanModel, related_name='upvoted_scans')
    favourites = models.ManyToManyField(ScanModel, related_name='favourite_scans')
    image = models.ImageField(
                                upload_to=user_directory_path,
                                blank=True,
                                null=True
                             )

    def __str__(self):
        return self.user.username + ' Profile'


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    '''
    Create user profile and images directory on user creation.
    :param sender: CustomUser object
    :param instance: CustomUser instance
    :param created: True if the user was created
    :param kwargs:
    :return:
    '''
    # Create user profile on user creation.
    if created:
        Profile.objects.create(user=instance)
        if not os.path.exists(os.path.join(MEDIA_ROOT, 'user_{0}/images/'.format(instance.id))):
            os.makedirs(os.path.join(MEDIA_ROOT, 'user_{0}/images').format(instance.id))
    instance.profile.save()


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    '''
    Save user profile when user is modified.
    :param sender: CustomUser object
    :param instance: CustomUser instance
    :param kwargs:
    :return:
    '''
    instance.profile.save()


@receiver(pre_delete, sender=CustomUser)
def delete_user_profile(sender, instance, **kwargs):
    '''
    Delete user profile when user is deleted.
    :param sender: CustomUser object
    :param instance: CustomUser instance
    :param kwargs:
    :return:
    '''
    instance.profile.delete()


@receiver(post_delete, sender=CustomUser)
def auto_delete_picture_on_delete(sender, instance, **kwargs):
    '''
    Delete profile picture when a user is deleted.
    :param sender: CustomUser object
    :param instance: CustomUser instance
    :param kwargs:
    :return:
    '''
    if instance.profile.image and os.path.isfile(instance.profile.image.path):
        os.remove(instance.profile.image.path)


@receiver(pre_save, sender=Profile)
def auto_delete_file_on_change(sender, instance, **kwargs):
    '''
    Delete profile old picture when it's changed.
    :param sender: Profile object
    :param instance: Profile instance
    :param kwargs:
    :return:
    '''
    if not instance.pk:
        return False

    try:
        old_file = Profile.objects.get(pk=instance.pk).image
    except Profile.DoesNotExist:
        return False

    new_file = instance.image
    if old_file and not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

scannect/scannect_web/forms/scan_forms.py
from django import forms

from ..models.scan_models import ScanModel


class UploadFileForm(forms.ModelForm):
    class Meta:
        model = ScanModel
        fields = (
            'name',
            'file',
            'preview_image',
        )

scannect/scannect_web/forms/user_forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from ..models.user_models import CustomUser, Profile


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(label="First name", max_length=25)
    last_name = forms.CharField(label="Last name", max_length=50)
    email = forms.EmailField(label="Email", max_length=254)

    class Meta:
        model = CustomUser
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2',
                  )

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()

        return user


class LoginForm(forms.Form):
    class Meta:
        model = CustomUser
        fields = ('username',
                  'password',
                  )

    username = forms.CharField(max_length=25)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Invalid login. Please try again.")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image',)


class EditUserForm(UserChangeForm):
    first_name = forms.CharField(label="First name", max_length=25)
    last_name = forms.CharField(label="Last name", max_length=50)
    email = forms.EmailField(label="Email", max_length=254)

    class Meta:
        model = CustomUser
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  'password'
                  )

    def save(self, commit=True):
        user = super(EditUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()

        return user

scannect/scannect_web/views/user.py
import json
from binascii import a2b_base64
import uuid
import os

from django.contrib.auth.decorators import login_required
from django.core.files import File
from django.shortcuts import get_list_or_404, get_object_or_404
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect
from django.http import HttpResponse

from ..business import get_user_models, save_preview_file, get_user_favourites, get_user_upvotes
from ..forms.scan_forms import UploadFileForm
from ..forms.user_forms import EditUserForm, EditProfileForm
from ..models.scan_models import ScanModel, user_image_path
from ..models.user_models import CustomUser
from scannect.settings import MEDIA_ROOT


@login_required
def upload(request):
    '''
    Method to upload scan models if the request method is POST.
    Otherwise return the view with the form to be able to upload it.
    :param request:
    :return:
    '''
    if request.method == 'POST':
        file_form = UploadFileForm(request.POST, request.FILES)
        if file_form.is_valid():
            file_model = file_form.save(commit=False)
            file_model.user = request.user
            file_model.save()
            if request.POST['preview_image']:
                pre_img = a2b_base64(request.POST['preview_image'].split('base64,')[1])
                path = user_image_path(file_model, '%s.png' % uuid.uuid4())
                image = open(os.path.join(MEDIA_ROOT, path), 'wb')
                image.write(pre_img)
                image.close()
                file_model.preview_image = path
                file_model.save()
            return redirect('home')
        else:
            return render(request, 'upload.html', {'file_form': file_form})
    else:
        file_form = UploadFileForm()
        return render(request, 'upload.html', {'file_form': file_form})


@login_required
def user_models(request):
    '''
    Get all scan models of the user who requested it.
    :param request:
    :return:
    '''
    models_list = get_user_models(request.user)

    page = request.GET.get('page', 1)

    paginator = Paginator(models_list, 12)
    try:
        models = paginator.page(page)
    except PageNotAnInteger:
        models = paginator.page(1)
    except EmptyPage:
        models = paginator.page(paginator.num_pages)

    return render(request, 'user_models.html', {'models': models})


@login_required
def edit(request, id):
    '''
    NOT USED. View for editing a scan model.
    :param request:
    :param id: Scan model ID
    :return:
    '''
    model = get_object_or_404(ScanModel, id=id)
    if request.method == 'POST':
        edit_form = UploadFileForm(request.POST, request.FILES, instance=model)
        if edit_form.is_valid():
            model = edit_form.save(commit=False)
            model.user = request.user
            model.save()
    else:
        edit_form = UploadFileForm(instance=model)
    return render(request, 'edit_model.html', {
        'edit_form': edit_form,
        'model_url': 'http://2.152.105.193:8000/media/' + str(model.file),
        'model_id': id
    })


@login_required
def delete_model(request, id):
    '''
    Delete a scan model.
    :param request:
    :param id: Scan model ID
    :return:
    '''
    if request.method == 'POST':
        try:
            ScanModel.objects.get(pk=id, user=request.user.id).delete()
        except ScanModel.DoesNotExist:
            messages.error(request, 'El modelo seleccionado no existe.')
    return redirect('myscans')

@login_required
def download_model(request, id):
    '''
    Download a scan model.
    :param request:
    :param id: Scan model ID
    :return:
    '''
    try:
        ScanModel.objects.get(pk=id).file
    except ScanModel.DoesNotExist:
        messages.error(request, 'El modelo seleccionado no existe.')
    return redirect('myscans')


@login_required
def profile(request):
    '''
    View of user profile.
    :param request:
    :return:
    '''
    return render(request, 'profile.html')


@login_required
def settings(request):
    '''
    Edit personal information about the request user.
    :param request:
    :return:
    '''
    password_form = PasswordChangeForm(user=request.user)
    if request.method == 'POST':
        form = EditUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            if request.FILES and 'image' in request.FILES:
                profile_form = EditProfileForm(request.POST, request.FILES, instance=request.user.profile)
                if profile_form.is_valid():
                    profile_form.save()
            return redirect('settings')
        else:
            return render(request, 'settings.html',
                          {
                              'edit_form': form,
                              'profile_form': profile_form,
                              'password_form': password_form,
                          })
    form = EditUserForm(instance=request.user)
    profile_form = EditProfileForm(instance=request.user.profile)
    return render(request, 'settings.html',
                  {
                      'edit_form': form,
                      'profile_form': profile_form,
                      'password_form': password_form,
                  })


@login_required
def upvote(request, id):
    '''
    API method. Upvote a scan model.
    :param request:
    :param id: Scan model id.
    :return: HttpResponse
    '''
    if request.method == 'POST':
        try:
            user = CustomUser.objects.get(pk=request.user.id)
            scan = ScanModel.objects.get(pk=id)
        except (ScanModel.DoesNotExist, CustomUser.DoesNotExist):
            return HttpResponse('Error', status=500)
        
        if scan.user == request.user:
            return HttpResponse('No autolike pls', status=500)

        if scan in get_user_upvotes(request.user):
            user.profile.upvotes.remove(scan)
            response_text = 'Upvoted successfully'
        else:
            user.profile.upvotes.add(scan)
            response_text = 'Upvote removed successfully'
        user.save()
        return HttpResponse(response_text, status=200)


@login_required
def favourite(request, id):
    '''
    API method. Add to favourites a scan model.
    :param request:
    :param id: Scan model id.
    :return: HttpResponse
    '''
    if request.method == 'POST':
        try:
            user = CustomUser.objects.get(pk=request.user.id)
            scan = ScanModel.objects.get(pk=id)
        except (ScanModel.DoesNotExist, CustomUser.DoesNotExist):
            return HttpResponse('Error', status=500)
        
        if scan.user == request.user:
            return HttpResponse('No autofav pls', status=500)

        if scan in get_user_favourites(request.user):
            user.profile.favourites.remove(scan)
            response_text = 'Added to favourite successfully'
        else:
            user.profile.favourites.add(scan)
            response_text = 'Removed from favourites successfully'
        user.save()
        return HttpResponse(response_text, status=200)


@login_required
def delete_account(request):
    '''
    Delete the request user account.
    :param request:
    :return:
    '''
    if request.method == 'POST':
        try:
            CustomUser.objects.get(pk=request.user.id).delete()
        except CustomUser.DoesNotExist:
            messages.error(request, 'No existe el usuario.')
    return redirect('home')


@login_required
def change_password(request):
    '''
    Change password of request user.
    :param request:
    :return:
    '''
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Password changed successfully')
        else:
            messages.error(request, "Couldn't change the password")
        return redirect('settings')


@login_required
def tmp_file(request):
    '''
    Save a temporary 3D file.
    :param request:
    :return: HttpResponse
    '''
    if request.method == 'POST' and request.FILES:
        stl_file = request.FILES['stl_file']
        if not stl_file.name.lower().endswith(('.stl', )):
            return HttpResponse(json.dumps({'message': 'File must be .stl'}), status=400)
        url = save_preview_file(stl_file)
        return HttpResponse(json.dumps({'url': url}), status=200)
    return HttpResponse(json.dumps({'message': 'The petition must be POST type and send a file'}), status=400)


@login_required
def favourites(request):
    '''
    View request user favourites scan models.
    :param request:
    :return:
    '''
    models_list = get_user_favourites(request.user)

    page = request.GET.get('page', 1)

    paginator = Paginator(models_list, 12)
    try:
        models = paginator.page(page)
    except PageNotAnInteger:
        models = paginator.page(1)
    except EmptyPage:
        models = paginator.page(paginator.num_pages)

    return render(request, 'user_favourites.html', {'models': models})

scannect/scannect_web/templates/download_scannect.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron" style="background-color: #E8E8E8; margin-top: 5%">
        <h1 class="display-4 text-center">Downloads</h1>
        <hr class="my-4">
        <div class="row text-center" style="margin-top: 1cm">
            <div class="col">
                <i class="fab fa-windows fa-7x"></i>
                <legend>Windows</legend>
            </div>
            <div class="col">
                <i class="fab fa-linux fa-7x"></i>
                <legend>Linux</legend>
                <p>Fedora 24:
                    <a href="/static/distros/distFedora.zip">Download</a>
                </p>
                <p>Ubuntu: 
                    <a href="/static/distros/distUbuntu.zip">Download</a>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

scannect/scannect_web/templates/edit_model.html
{% extends 'base.html' %}
{% block title %}
    Edit model
{% endblock %}
{% block scripts %}
    {% load static %}
    <script src="{% static "js/stlViewerController.js" %}"></script>
    <script src="{% static "js/uploadSTL.js" %}"></script>
{% endblock %}
{% block content %}
    <br><br>
    <form enctype="multipart/form-data" action="{% url 'edit' id=model_id %}" class="form-horizontal main-login main-center" method="post">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <button type="submit">Upload</button>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
    </form>

    <iframe id="vs_iframe" src="http://www.viewstl.com/?embedded&url={{ model_url }}&local&bgcolor=green&color=white&shading=flat&rotation=yes&clean=yes&noborder=yes&orientation=front&edges=no" style="border:0;margin:0;width:100%;height:100%;"></iframe>

{% endblock %}

scannect/scannect_web/templates/info_profile.html
<div class="form-horizontal" style="padding: 1cm">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                {% csrf_token %}
                <div class="form-group text-center">
                    <b>{{ request.user }} </b>
                    <p>{{ request.user.email }} </p>
                </div>
            </div>
        </div>
    </div>
    

scannect/scannect_web/templates/profile.html
{% extends 'base.html' %}
{% block title %}
    Profile
{% endblock %}
{% block content %}
    {{ request.user.username }}<br />
    {{ request.user.first_name }}<br />
    {{ request.user.last_name }}<br />
    {{ request.user.email }}<br />
    <img class="img-fluid img-thumbnail" style="width: 200px; height: 200px; border-radius: 50%"
         src="
            {% if request.user.profile.image %}
                {{ request.user.profile.image.url }}
            {% else %}
                /static/img/shrek.jpg
            {% endif %}" alt="">
    <a href="{% url 'edit_profile' %}">Editar</a>
    <form method="POST" action="{% url 'delete_account' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete account</button>
    </form>
{% endblock %}

scannect/scannect_web/templates/settings.html
{% extends 'base.html' %}
{% block title %}
    Settings
{% endblock %}

{% block scripts %}

    <script>

    $( document ).ready(function () {

        $('#id_image').on('change', function () {

             if (this.files && this.files[0]) {
                 var reader = new FileReader();
                 reader.onload = function(e) {
                     $('img#profile_picture').attr('src',e.target.result);
                 };
                 reader.readAsDataURL(this.files[0]);
             }
        });

    });
    </script>

{% endblock %}

{% block content %}
<div style="margin-top: 4%">
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link {% if not messages and not edit_form.errors and not profile_form.errors %} active {% endif %}" id="nav-home-tab" style="color: #00a379" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Profile</a>
            <a class="nav-item nav-link {% if messages or edit_form.errors  or profile_form.errors  %} active {% endif %}" id="nav-profile-tab" style="color: #00a379" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Edit</a>
        </div>
    </nav>
    <div class="tab-content main-login" style="border-top-left-radius: 0px;" id="nav-tabContent">
        <div style="height: 50px" class=" text-center">
            <img class="img-fluid img-thumbnail" 
            style=" z-index: 1;width: 150px; margin-top: -75px; height: 150px; border-radius: 50%"
            id="profile_picture"
            src="
                    {% if request.user.profile.image %}
                        {{ request.user.profile.image.url }}
                    {% else %}
                        /static/img/shrek.jpg
                    {% endif %}"
            alt="">
        </div>
        <div class="tab-pane fade {% if not messages and not edit_form.errors and not profile_form.errors %} show active {% endif %}" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
            {% include 'info_profile.html' %}
        </div>
        <div class="tab-pane fade {% if messages or edit_form.errors or profile_form.errors %} show active {% endif %}" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
            {% include 'edit_profile.html' %}
        </div>
    </div>
</div>
  {% endblock %}

scannect/scannect_web/templates/signup.html
{% extends 'base.html' %}

{% block title %}
    SignUp
{% endblock %}
{% block content %}
    <form action="signup" class="form-horizontal main-login main-center" method="post">
        {% csrf_token %}
        <h1>Sign Up</h1>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label class="control-label">First name: </label>
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text"><i class="fas fa-font" aria-hidden="true"></i></div>
                        </div>
                        <input 
                        class=" form-control input-md {% if signup_form.errors.first_name %} input-error {% endif %}" 
                        type="text" name="first_name" maxlength="25" required id="id_first_name">
                    </div>
                    {% if signup_form.errors.first_name %}
                    <div class="alert alert-dismissible fade show alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong class="form-text text-muted">{{ signup_form.first_name.errors.as_text }}</strong>
                    </div>
                    {% endif %}
                    <label class="control-label">Last name: </label>
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text"><i class="fas fa-font" aria-hidden="true"></i></div>
                        </div>
                        <input 
                        class="{% if signup_form.errors.last_name %} input-error {% endif %} form-control input-md" 
                        type="text" name="last_name" maxlength="50" required id="id_last_name">
                    </div>
                    {% if signup_form.errors.last_name %}
                    <div class="alert alert-dismissible fade show alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong class="form-text text-muted">{{ signup_form.last_name.errors.as_text }}</strong>
                    </div>
                    {% endif %}
                    <label class="control-label">Email: </label>
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text">@</div>
                        </div>
                        <input type="email" name="email" maxlength="254" required 
                        class="form-control input-md {% if signup_form.errors.email %} input-error {% endif %}" id="id_email">
                    </div>
                    {% if signup_form.errors.email %}
                    <div class="alert alert-dismissible fade show alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong class="form-text text-muted">{{ signup_form.email.errors.as_text }}</strong>
                    </div>
                    {% endif %}
                    <label class="control-label">Username: </label>
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fas fa-user"></i>
                            </div>
                        </div>
                        <input type="text" name="username" maxlength="150" autofocus="" required 
                        class="form-control input-md {% if signup_form.errors.username %} input-error {% endif %}" id="id_username">
                        <small class="text-muted">{{ signup_form.username.help_text }}</small>
                    </div>
                    {% if signup_form.errors.username %}
                    <div class="alert alert-dismissible fade show alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong class="form-text text-muted">{{ signup_form.username.errors.as_text }}</strong>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-6">
                <label class="control-label">Password: </label>
                <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <i class="fas fa-lock"></i>
                        </div>
                    </div>
                    <input type="password" name="password1" required 
                    class="form-control input-md {% if signup_form.errors.first_name %} input-error {% endif %}" id="id_password1">
                    <small class="form-text text-muted">{{ signup_form.password1.help_text|safe }}</small>
                </div>
                {% if signup_form.errors.password1 %}
                <div class="alert alert-dismissible fade show alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong class="form-text text-muted">{{ signup_form.password1.errors.as_text }}</strong>
                </div>
                {% endif %}
                <label class="control-label">Password confirmation: </label>
                <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <i class="fas fa-check"></i>
                        </div>
                    </div>
                    <input type="password" name="password2" required 
                    class="form-control input-md {% if signup_form.errors.first_name %} input-error {% endif %}" id="id_password2">
                    <small class="text-muted">{{ signup_form.password2.help_text }}</small>
                </div>
                {% if signup_form.errors.password2 %}
                <div class="alert alert-dismissible fade show alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong class="form-text text-muted">{{ signup_form.password2.errors.as_text }}</strong>
                </div>
                {% endif %}
            </div>
        </div>
        <!-- {% if signup_form.errors %}
        {% for field in signup_form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in signup_form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
        {% endif %} -->
        <div class="text-center">
            <button type="submit" class=" text-center btn xboxgreen">Sign up</button>
        </div>
    </form>

{% endblock %}